---
cronjob:
  concurrencyPolicy: Forbid
  environment:
    # CDK value: (Cloud Developer's Kit) development identity platform
    # CDM value: CDM (Cloud Deployment Model) identity cloud platform
    # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
    frPlatformType: FIDC
    # RaiseForStatus will exit if go resty returns an error in STRICT mode,
    # be it client error, server error or other. Turning off (false)
    # STRICT mode will simply warn of client/server errors.
    strict: true
  image:
    # repo: 
    # tag:
    imagePullPolicy: Always
  schedule: "* * * * *"
  seccessfulJobHistoryLimit: 1
  startingDeadlineSeconds: 180
  restartPolicy: OnFailure
