name: merge

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: secureopenbanking-uk-iam-initializer
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          make test-ci

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
      
      - name: docker build
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }}
          docker tag ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
          docker push ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
